#!/usr/bin/php
<?php
/**
 * params
 *
 * Demo de como pasar parametros
 *
 * PHP version 5.3
 *
 * Copyright (c) 2013 mostofreddy <mostofreddy@gmail.com>
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 *
 * @category   Clip/Samples
 * @package    Clip
 * @subpackage Clip/Samples
 * @author     Federico Lozada Mosto <mostofreddy@gmail.com>
 * @copyright  2013 Federico Lozada Mosto <mostofreddy@gmail.com>
 * @license    MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link       http://www.mostofreddy.com.ar
 */
require_once '../src/clip/Clip.php';
require_once '../src/clip/Opts.php';
require_once '../src/clip/Writer.php';

/**
 * Clase Test
 *
 * @category  Clip
 * @package   Clip
 * @author    Federico Lozada Mosto <mostofreddy@gmail.com>
 * @copyright 2013 Federico Lozada Mosto <mostofreddy@gmail.com>
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link      http://www.mostofreddy.com.ar
 */
class Test extends \clip\Clip
{
    /**
     * Valida los datos de entrada
     *
     * @param \clip\Opts $opts objeto \clip\Opts
     *
     * @return true|string si no hubo error devuelve true, de lo contrario el mensaje de error
     */
    protected function validate(\clip\Opts $opts)
    {
        return true;
    }
    /**
     * Imprime la ayuda en pantalla
     *
     * @return void
     */
    protected function help()
    {
        $help = <<<HELP
Examples
Usage: ./params --version
Usage: ./params --help
Usage: ./params -vup --nombre=federico /path/to/file.php

--version                      Prints the version and exits.
--help | -h                    Prints this usage information.
HELP;
        $this->writer->write($help, null, null, true)
            ->nl();
    }
    /**
     * Imprime la version en pantalla
     *
     * @return void
     */
    protected function version()
    {
        $version = <<<VERSION
params 1.0.0 (cli)
Copyright (c) 2013 Mostofreddy
VERSION;
        $this->writer->write($version, null, null, true)
            ->nl();
    }
    /**
     * run method
     *
     * @return void
     */
    public function run()
    {
        parent::run();
        $this->writer->write("Los parametros se optienen mediante el objeto \clip\Opts")
            ->nl();

        $this->writer->write("Short params", 'yellow')
            ->nl()
            ->write(print_r($this->opts->short, true))
            ->nl();

        $this->writer->write("Long params", 'yellow')
            ->nl()
            ->write(print_r($this->opts->long, true))
            ->nl();

        $this->writer->write("Input params", 'yellow')
            ->nl()
            ->write(print_r($this->opts->input, true))
            ->nl();
    }
}

$opts = new \clip\Opts();
$opts->read();
$writer = new \clip\Writer();
$clip = new Test();
$clip->opts($opts);
$clip->writer($writer);
$clip->run();
