#!/usr/bin/php
<?php
/**
 * validation
 *
 * Demo para validar parametros que vienen por linea de comando
 *
 * PHP version 5.3
 *
 * Copyright (c) 2013 mostofreddy <mostofreddy@gmail.com>
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 *
 * @category   Cliptools/Samples
 * @package    Cliptools
 * @subpackage Cliptools/Samples
 * @author     Federico Lozada Mosto <mostofreddy@gmail.com>
 * @copyright  2013 Federico Lozada Mosto <mostofreddy@gmail.com>
 * @license    MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link       http://www.mostofreddy.com.ar
 */
require_once '../src/cliptools/Cli.php';
require_once '../src/cliptools/Opts.php';
require_once '../src/cliptools/Writer.php';

/**
 * Clase Test
 *
 * @category  Cliptools
 * @package   Cliptools
 * @author    Federico Lozada Mosto <mostofreddy@gmail.com>
 * @copyright 2013 Federico Lozada Mosto <mostofreddy@gmail.com>
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link      http://www.mostofreddy.com.ar
 */
class Test extends \cliptools\Cli
{
    /**
     * Valida los datos de entrada
     *
     * @param \cliptools\Opts $opts objeto \cliptools\Opts
     *
     * @return true|string si no hubo error devuelve true, de lo contrario el mensaje de error
     */
    protected function validate(\cliptools\Opts $opts)
    {
        if(!in_array("t", $opts->short)) {
            return "No se agrego la opcion t";
        }
        if (!array_key_exists("nombre", $opts->long)) {
            return "No se indico el nombre";
        }
        return true;
    }
    /**
     * Imprime la ayuda en pantalla
     *
     * @return void
     */
    protected function help()
    {
        $help = <<<HELP
Examples
Usage: ./validation --version
Usage: ./validation --help
Usage: ./validation -t --nombre=federico

--version                      Prints the version and exits.
--help | -h                    Prints this usage information.
HELP;
        $this->writer->write($help, null, null, true)
            ->nl();
    }
    /**
     * Imprime la version en pantalla
     *
     * @return void
     */
    protected function version()
    {
        $version = <<<VERSION
validation 1.0.0 (cli)
Copyright (c) 2013 Mostofreddy
VERSION;
        $this->writer->write($version, null, null, true)
            ->nl();
    }
    /**
     * run method
     *
     * @return void
     */
    public function run()
    {
        parent::run();
        $this->writer->write("El nombre ingresado fue: ")
            ->write($this->opts->long['nombre'], "green")
            ->nl();
    }
}

$opts = new \cliptools\Opts();
$opts->read();
$writer = new \cliptools\Writer();
$clip = new Test();
$clip->opts($opts);
$clip->writer($writer);
$clip->run();
